src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà pris!")
 * @UniqueEntity(fields={"username"}, message="Ce pseudo est déjà pris!")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(
     *     message="Veuillez renseigner votre pseudo!"
     * )
     * @Assert\Length(
     *     min=3,
     *     max=50,
     *     minMessage="{{ limit }} caractères minimum svp!",
     *     maxMessage="{{ limit }} caractères maximum svp!"
     * )
     * @Assert\Regex(
     *     pattern="/^[\w]*$/",
     *     message="Seuls les caractères alphanumériques et _ sont acceptés!"
     * )
     * @ORM\Column(type="string", length=50, unique=true)
     * @Groups({"import_csv"})
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Groups({"import_csv"})
     */
    private $password;

    /**
     * @Assert\NotBlank(
     *     message="Veuillez renseigner votre nom!"
     * )
     * @Assert\Length(
     *     min=3,
     *     max=250,
     *     minMessage="{{ limit }} caractères minimum svp!",
     *     maxMessage="{{ limit }} caractères maximum svp!"
     * )
     * @ORM\Column(type="string", length=250)
     * @Groups({"import_csv"})
     */
    private $last_name;

    /**
     * @Assert\NotBlank(
     *     message="Veuillez renseigner votre prénom!"
     * )
     * @Assert\Length(
     *     min=3,
     *     max=250,
     *     minMessage="{{ limit }} caractères minimum svp!",
     *     maxMessage="{{ limit }} caractères maximum svp!"
     * )
     * @ORM\Column(type="string", length=250)
     * @Groups({"import_csv"})
     */
    private $first_name;

    /**
     * @Assert\NotBlank(
     *     message="Veuillez renseigner votre email!"
     * )
     * @Assert\Length(
     *     min=6,
     *     max=250,
     *     minMessage="{{ limit }} caractères minimum svp!",
     *     maxMessage="{{ limit }} caractères maximum svp!"
     * )
     * @ORM\Column(type="string", length=250)
     * @Groups({"import_csv"})
     */
    private $email;

    /**
     * @Assert\NotBlank(
     *     message="Veuillez renseigner votre téléphone!"
     * )
     * @Assert\Regex(
     *     pattern="/^(0|(\\+33)|(0033))[1-9][0-9]{8}$/",
     *     message="Votre numéro de téléphone n'est pas valide!"
     * )
     * @ORM\Column(type="string", length=15)
     * @Groups({"import_csv"})
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"import_csv"})
     */
    private $active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_updated;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    /**
     * @ORM\ManyToMany(targetEntity=Trip::class, mappedBy="participants")
     */
    private $participatingTrips;

    /**
     * @ORM\OneToMany(targetEntity=Trip::class, mappedBy="organiser")
     */
    private $organisedTrips;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $pictureFileName;

    public function __construct()
    {

        $this->participatingTrips = new ArrayCollection();
        $this->organisedTrips = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->date_updated;
    }

    public function setDateUpdated(?\DateTimeInterface $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    /**
     * @return Collection|Trip[]
     */
    public function getParticipatingTrips(): Collection
    {
        return $this->participatingTrips;
    }

    public function addParticipatingTrip(Trip $participatingTrip): self
    {
        if (!$this->participatingTrips->contains($participatingTrip)) {
            $this->participatingTrips[] = $participatingTrip;
            $participatingTrip->addParticipant($this);
        }

        return $this;
    }

    public function removeParticipatingTrip(Trip $participatingTrip): self
    {
        if ($this->participatingTrips->removeElement($participatingTrip)) {
            $participatingTrip->removeParticipant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Trip[]
     */
    public function getOrganisedTrips(): Collection
    {
        return $this->organisedTrips;
    }

    public function addOrganisedTrip(Trip $organisedTrip): self
    {
        if (!$this->organisedTrips->contains($organisedTrip)) {
            $this->organisedTrips[] = $organisedTrip;
            $organisedTrip->setOrganiser($this);
        }

        return $this;
    }

    public function removeOrganisedTrip(Trip $organisedTrip): self
    {
        if ($this->organisedTrips->removeElement($organisedTrip)) {
            // set the owning side to null (unless already changed)
            if ($organisedTrip->getOrganiser() === $this) {
                $organisedTrip->setOrganiser(null);
            }
        }

        return $this;
    }

    public function getPictureFileName(): ?string
    {
        return $this->pictureFileName;
    }

    public function setPictureFileName(?string $pictureFileName): self
    {
        $this->pictureFileName = $pictureFileName;

        return $this;
    }
}

src/Controller/TripController.php
<?php

namespace App\Controller;

use App\Entity\Trip;
use App\Entity\User;
use App\Form\CancelTripType;
use App\Form\TripType;
use App\Repository\StateRepository;
use App\Repository\TripRepository;
use App\Services\Updater;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TripController extends AbstractController
{
    /**
     * @var Updater
     */
    private Updater $updater;

    private array $states;

    public function __construct(Updater $updater)
    {
        $this->updater = $updater;
        $this->states = $this->updater->states;
    }

    /**
     * @Route("/trip/{id}", name="trip_getDetail")
     * @param $id
     * @param TripRepository $tripRepository
     * @return Response
     * @throws NonUniqueResultException
     */
    public function getDetail(int $id, TripRepository $tripRepository): Response
    {
        $tripDetail = $tripRepository->findNotArchived($id);

        return $this->render('trip/detail.html.twig', [
            'tripDetail' => $tripDetail,
            'states' => $this->states
        ]);
    }

    /**
     * @Route("/create", name="trip_create")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $trip = new Trip();
        $form = $this->createForm(TripType::class, $trip);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //Définition du bouton qui a permis l'envoi du formulaire
            $button = $form->getClickedButton()->getName();
            if ($button == 'create') {
                $state = $this->states['created'];
                $flashMessage = 'Votre sortie a bien été créée';
            } else {
                $state = $this->states['opened'];
                $flashMessage = 'Votre sortie a bien été publiée';
            }

            $user = $this->getUser();

            //Traitement
            $trip->setState($state);
            $trip->setOrganiser($user);
            $trip->setOrganiserCampus($user->getCampus());

            $entityManager->persist($trip);
            $entityManager->flush();

            $this->addFlash('success', $flashMessage);

            //Redirection
            return $this->redirectToRoute('trip_getDetail', ['id' => $trip->getId()]);
        }

        $location = $trip->getLocation();

        return $this->render('trip/createTrip.html.twig', [
            'tripForm' => $form->createView(),
            'location' => $location
        ]);
    }

    /**
     * @Route("/modify-{id}", name="trip_modify")
     * @param int $id
     * @param Request $request
     * @param TripRepository $tripRepository
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function modify(int $id, Request $request, TripRepository $tripRepository, EntityManagerInterface $manager): Response
    {
        $user = $this->getUser();
        $trip = $tripRepository->findWithoutParticipants($id, $user);

        //Interdiction de la modification de la sortie si celle-ci n'est pas ouverte
        if ($this->states['created'] !== $trip->getState()){
            $this->addFlash('danger', 'Vous ne pouvez plus modifier cette sortie!');
            return $this->redirectToRoute('main_home');
        }

        $form = $this->createForm(TripType::class, $trip);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $flashMessage = 'Votre sortie a bien été modifiée';

            //Définition du bouton qui a permis l'envoi du formulaire
            $button = $form->getClickedButton()->getName();
            if ($button == 'opened') {
                $trip->setState($this->states['opened']);
                $flashMessage = 'Votre sortie a bien été modifiée et publiée';
            }

            $manager->persist($trip);
            $manager->flush();

            $this->addFlash('success', $flashMessage);

            //Redirection
            return $this->redirectToRoute('trip_getDetail', ['id' => $trip->getId()]);
        }

        $location = $trip->getLocation();

        return $this->render('trip/modifyTrip.html.twig', [
            'tripForm' => $form->createView(),
            'location' => $location,
            'states' => $this->states,
            'trip' => $trip,
        ]);
    }

    /**
     * @Route("trip/cancel/{id}", name="trip_cancel", requirements={"id"="\d+"})
     * @param int $id
     * @param Request $request
     * @param TripRepository $tripRepository
     * @param EntityManagerInterface $manager
     * @return Response
     * @throws NonUniqueResultException
     */
    public function cancelTrip(int $id, Request $request, TripRepository $tripRepository, EntityManagerInterface $manager): Response
    {

        /** @var User $user */
        $user = $this->getUser();
        $trip = $tripRepository->findNotArchived($id);

        //Vérification de l'existence de la sortie
        if (!$trip) {
            $this->addFlash('warning', "Cette sortie n'existe pas !");
            return $this->redirectToRoute('main_home' );
        }

        $form = $this->createForm(CancelTripType::class, $trip);
        $tripState = $trip->getState();
        $now = new \DateTime();
        $oldDetailTrip = $trip->getDetails();

        //Vérification de la possibilité d'annulation
        if ($trip->getOrganiser() !== $user
            || $trip->getDateTimeStart() < $now
            || $tripState == $this->states['canceled']
            || $tripState == $this->states['created']) {

            $this->addFlash('warning', 'Vous ne pouvez pas annuler cette sortie !');
            return $this->redirectToRoute('trip_getDetail', ['id' => $trip->getId()]);
        }

        $form->handleRequest($request);

        //Traitement
        if ($form->isSubmitted() && $form->isValid()) {
            $cancelDetailTrip = $form['details']->getData();
            $text_cancel = $oldDetailTrip ." Motif d'annulation : " .$cancelDetailTrip;
            $trip->setDetails($text_cancel);

            $trip->setState($this->states['canceled']);

            $manager->persist($trip);
            $manager->flush();

            $this->addFlash('success', 'Votre sortie a été annulée');
            return $this->redirectToRoute('trip_getDetail', ['id' => $trip->getId()]);
        }

        return $this->render('trip/cancelTrip.html.twig', [
            'trip' => $trip,
            'formCancelTrip' => $form->createView()
        ]);
    }
}

templates/trip/cancelTrip.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
{% endblock %}

{% block title %}{{ parent() }} - Annuler{% endblock %}

{% block body %}
    <section class="container min-vh-100">
        <h1 class="text-center my-5">Annuler une sortie !</h1>
        <article class="container-fluid my-4 row d-flex justify-content-center">
            <div class="d-flex justify-content-between col-7 mt-4">
                <span>Nom de la sortie : </span><span>{{ trip.name }}</span>
            </div>
            <div class="d-flex justify-content-between col-7 mt-4">
                <span>Date de la sortie : </span><span>{{ trip.dateTimeStart | date('d/m/Y') }}</span>
            </div>
            <div class="d-flex justify-content-between col-7 mt-4">
                <span>Campus : </span><span>{{ trip.organiserCampus.name }}</span>
            </div>
            <div class="d-flex justify-content-between col-7 mt-4">
                <span>Lieu : </span><span>{{ trip.location.name }} {{ trip.location.city.zipCode }} {{ trip.location.city.name }}</span>
            </div>
            <div id="form_cancel_trip" class="d-flex justify-content-between col-7 mt-4">
                {{ form_start(formCancelTrip) }}
                {{ form_row(formCancelTrip.details) }}
            </div>
            <div class="d-flex justify-content-between col-7 mt-4">
                <a class="btn btn-blue-light col-4" href="{{ path('trip_getDetail', {id:trip.id}) }}">Annuler</a>
                {{ form_row(formCancelTrip.confirm) }}
            </div>
                {{ form_end(formCancelTrip) }}
        </article>
    </section>
{% endblock %}

templates/trip/createTrip.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    <script src="{{ asset('js/ajax/tripForm.js') }}"></script>
{% endblock %}

{% block title %}{{ parent() }} Créer une sortie{% endblock %}

{% block body %}
    <section class="container">
        <h1 class="text-center mb-5 mt-5">Créer une sortie !</h1>
        <article id="formTrip" class="mb-5">
            {{ form_start(tripForm) }}
            <aside class="d-flex justify-content-between">
                <div class="col-md-6 col-12">
                    {{ form_row(tripForm.name) }}
                    {{ form_row(tripForm.dateTimeStart) }}
                    {{ form_row(tripForm.dateLimitForRegistration) }}
                    {{ form_row(tripForm.maxRegistrationNumber, {'type':'number'}) }}
                    {{ form_row(tripForm.duration, {'type':'number'}) }}
                    {{ form_row(tripForm.details) }}
                </div>
                <div class="col-md-5 col-12">
                    <div class="form-group">
                        <span>Campus :</span><span>{{ app.user.campus.name }}</span>
                    </div>
                    <div class="form-group">
                        {{ form_row(tripForm.city) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(tripForm.location) }}
                    </div>
                    <div id="location-infos">
                        <div class="form-group">
                            Rue :<span id="street">{{ location is not null ? location.street : '' }}</span>
                        </div>
                        <div class="form-group">
                            Code Postal :<span id="zipCode">{{ location is not null ? location.city.zipCode : '' }}</span>
                        </div>
                        <div class="form-group">
                            Latitude :<span id="latitude">{{ location is not null ? location.latitude : '' }}</span>
                        </div>
                        <div class="form-group">
                            Longitude :<span id="longitude">{{ location is not null ? location.longitude : '' }}</span>
                        </div>
                    </div>
                </div>
            </aside>

            <div class="mt-5 d-flex justify-content-between align-items-center trip_buttons">
                <div class="col-4 mr-5">
                    {{ form_row(tripForm.create) }}
                </div>
                <div class="col-4 mr-5">
                    {{ form_row(tripForm.publish) }}
                </div>
                <a class="btn btn-blue-light-retour col-3 ml-5" href="{{ path('main_home') }}">Annuler</a>
            </div>
            {{ form_end(tripForm) }}
        </article>
    </section>
    <section class="container">

    </section>
{% endblock %}

templates/trip/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if tripDetail is null %}
        Sortie non consultable
    {% else %}
        {{ parent() }} {{ tripDetail.name }}
    {% endif %}
{% endblock %}

{% block body %}
    <div class="container-fluid bg-light px-5 py-5 min-vh-100">

        {% if tripDetail is null %}
            <h2 class="text-center mb-5">Désolé, cette sortie n'est plus consultable</h2>

        {% else %}
            <h2 class="text-center mb-5">{{ tripDetail.name }}</h2>
            <div class="row justify-content-around">
                <div class="col-sm-12 col-md-6">
                    <ul class="list-group">
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Nom de la sortie:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.name }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Date et heure de la sortie:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.dateTimestart | date("d/m/Y") }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Date limite d'inscription:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.dateLimitForRegistration | date("d/m/Y") }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Nombre de places:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.participants | length }}/{{ tripDetail.maxRegistrationNumber }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Durée:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.duration }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Description et infos:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.details }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Campus:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.organiserCampus.name }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Lieu:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.location.name }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Rue:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.location.street }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Code postal:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.location.city.zipCode }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Latitude:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.location.latitude }}
                            </div>
                        </li>
                        <li class="list-group-item d-flex">
                            <div class="col-4">
                                Longitude:
                            </div>
                            <div class="col-8">
                                {{ tripDetail.location.longitude }}
                            </div>
                        </li>
                    </ul>
                </div>

                <div id="trip_organisateur" class="col-sm-12 col-md-4 mt-5">
                    <h5 class="mb-2 pt-3">Organisateur</h5>
                    <a href="{{ path('profil_show', {id:tripDetail.organiser.id}) }}"><li class="list-group-item d-flex">
                        <div class="col-6">
                            {{ tripDetail.organiser.username }}
                        </div>
                        <div class="col-6">
                            {{ tripDetail.organiser.firstName }} {{ tripDetail.organiser.lastName }}
                        </div>
                    </li></a>

                    {% if tripDetail.participants is not empty %}
                        <h5 class="mb-2 pt-5">Liste des participants</h5>
                            <ul id="table-head-participants" class="list-group">
                                <li class="list-group-item d-flex" id="participants-list-head">
                                    <div class="col-6">
                                        Pseudo
                                    </div>
                                    <div class="col-6">
                                        Nom
                                    </div>
                                </li>
                            </ul>
                            <ul id="table-participants" class="participants-list list-group">
                                {% for participant in tripDetail.participants %}
                                    <a href="{{ path('profil_show', {id:participant.id}) }}">
                                        <li class="list-group-item d-flex">
                                            <div class="col-6">
                                                {{ participant.username }}
                                            </div>
                                            <div class="col-6">
                                                {{ participant.firstName }} {{ participant.lastName }}
                                            </div>
                                        </li>
                                    </a>
                                {% endfor %}
                            </ul>
                    {% endif %}
                    {% if tripDetail.organiser == app.user %}
                        <div id="trip_detail" class="my-4 d-flex justify-content-between">
                            {% if tripDetail.state == states.opened %}
                                <a class="btn btn-blue-light col-5" href="{{ path('trip_cancel', {id:tripDetail.id}) }}">Annuler la sortie</a>
                            {% elseif tripDetail.state == states.created %}
                                <a class="btn btn-blue-light col-5" href="{{ path('trip_modify', {id:tripDetail.id}) }}">Modifier la sortie</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/trip/modifyTrip.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    <script src="{{ asset('js/ajax/tripForm.js') }}"></script>
{% endblock %}

{% block title %}{{ parent() }} Modifier une sortie{% endblock %}

{% block body %}
    <section class="container">
        <h1 class="text-center mb-5 mt-5">Modifier une sortie !</h1>
        <article id="formTrip" class="mb-5">
            {{ form_start(tripForm) }}
            <aside class="d-flex justify-content-between">
                <div class="col-md-6 col-12">
                    {{ form_row(tripForm.name) }}
                    {{ form_row(tripForm.dateTimeStart) }}
                    {{ form_row(tripForm.dateLimitForRegistration) }}
                    {{ form_row(tripForm.maxRegistrationNumber, {'type':'number'}) }}
                    {{ form_row(tripForm.duration, {'type':'number'}) }}
                    {{ form_row(tripForm.details) }}
                </div>
                <div class="col-md-5 col-12">
                    <div class="form-group">
                        {{ form_row(tripForm.organiserCampus) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(tripForm.city) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(tripForm.location) }}
                    </div>
                    <div id="location-infos">
                        <div class="form-group">
                            Rue :<span id="street"> {{ location is not null ? location.street : '' }} </span>
                        </div>
                        <div class="form-group">
                            Code Postal :<span id="zipCode">{{ location is not null ? location.city.zipCode : '' }}</span>
                        </div>
                        <div class="form-group">
                            Latitude :<span id="latitude">{{ location is not null ? location.latitude : '' }}</span>
                        </div>
                        <div class="form-group">
                            Longitude :<span id="longitude">{{ location is not null ? location.longitude : '' }}</span>
                        </div>
                    </div>
                </div>
            </aside>

            <div class="mt-5 d-flex justify-content-between align-items-center trip_buttons">
                <div class="col-4 mr-5">
                    {{ form_row(tripForm.create) }}
                </div>
                {% if states.created == trip.state %}
                    <div class="col-4 mr-5">
                        {{ form_row(tripForm.publish) }}
                    </div>
                {% endif %}
                <a class="btn btn-blue-light-retour col-3 ml-5" href="{{ path('main_home') }}">Annuler</a>
            </div>
            {{ form_end(tripForm) }}
        </article>
    </section>
{% endblock %}